---
repository: atamanroman/atamanroman.github.io
url: https://www.atamanroman.dev
title: atamanroman.dev
description: 'My Personal Space: IT, Development, Software Architecture and Things I Care About'
favicon: favicon.svg
lsi: false
safe: true
incremental: false
exclude:
  - TODO.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - dev.sh
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
remote_theme: riggraz/no-style-please
theme_config:
  appearance: auto
  back_home_text: cd ..
  date_format: '%Y-%m-%d'
  show_description: true
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jemoji
whitelist:
  - jekyll-redirect-from
defaults:
  - scope:
      path: cvs/**/*
    values:
      sitemap: false
