baseURL = "https://www.atamanroman.dev/"
languageCode = "en-us"
title = "atamanroman.dev"
pygmentsCodeFences = true
theme = "smol"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  cv = "cv.html"

[params]
  subtitle = ""
  favicon = "favicon.svg"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNoStart = 1
    lineNos = true
    noClasses = true
    # "manni" works well, too
    style = "emacs"
    tabWidth = 2

# Header
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv.html"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

# Footer
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/atamanroman"
    weight = 1
  [[menu.footer]]
    name = "Twitter"
    url = "https://twitter.com/atamanroman"
    weight = 2
  [[menu.footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/atamanroman"
    weight = 3
  [[menu.footer]]
    name = "XING"
    url = "https://www.xing.com/profile/Roman_Ataman"
    weight = 3
  [[menu.footer]]
    name = "StackOverflow"
    url = "https://stackoverflow.com/users/366299/atamanroman"
    weight = 4
  [[menu.footer]]
    name = "Medium"
    url = "https://medium.com/@atamanroman"
    weight = 5
